version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
  groups:
    code-analysis-set:
      patterns:
      - "Microsoft.CodeAnalysis"
      - "Microsoft.CodeAnalysis.CSharp"
      - "Microsoft.CodeAnalysis.CSharp.Workspaces"

    code-analysis-other:
      patterns:
      - "Microsoft.CodeAnalysis*"
      exclude-patterns:
      - "Microsoft.CodeAnalysis"
      - "Microsoft.CodeAnalysis.CSharp"
      - "Microsoft.CodeAnalysis.CSharp.Workspaces"

    microsoft:
      patterns:
      - "Microsoft*"
      - "System*"
      - "MSTest*"
      # Define patterns to exclude dependencies from the group (based on
      # dependency name)
      exclude-patterns:
      - "Microsoft.CodeAnalysis*"
  open-pull-requests-limit: 20
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every weekday
    interval: weekly  
  open-pull-requests-limit: 20
