version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
  groups:
    code-analysis-set:
      patterns:
      - "Microsoft.CodeAnalysis"
      - "Microsoft.CodeAnalysis.CSharp"

    code-analysis-other:
      patterns:
      - "Microsoft.CodeAnalysis*"

    microsoft:
      patterns:
      - "Microsoft*"
      - "System*"
      - "MSTest*"
  open-pull-requests-limit: 20
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every weekday
    interval: weekly  
  open-pull-requests-limit: 20
