<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\StyleSharp.Analyzers\StyleSharp.Analyzers.csproj" />
    <ProjectReference Include="..\..\StyleSharp.Analyzers.CodeFixes\StyleSharp.Analyzers.CodeFixes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="RoslynCommon.Analyzers" />
  </ItemGroup>

</Project>
